### PR TITLE
Port to TrombLoader 2

### PR DESCRIPTION
**Pull request by hedgehog1029**
- Replace TrombLoader "API" (read: public methods that happened to be available at the time) calls with BaboonAPI calls
    - TrombLoader 2 stabilizes the API a bit, `folderPath` has docs and is considered API
    - ... though I'd like to do zip loading in v2.1.0, which may throw a spanner in the works. eh, we'll see
- Run "remove unused `using` directives", creating an incredibly noisy PR (ok but it was bugging me)
- Replace direct dll paths in csproj with `<PackageReference>`s
    - ~~If you want me to put that PostBuild task back just lmk~~ done

### CODE REVIEW

**Comment by hedgehog1029** [comment]
_ignore the force push, everything is fine_

This probably shouldn't be merged until trombloader 2 is fully ready to go since it's incompatible with trombloader 1. mostly it's just a couple things i want to do in BaboonAPI before we go, but there's documentation to write too.

**Comment by clydejallorina** [comment]
Noted, did a quick look through the PR and we're most likely keeping the `<PostBuild>` since it makes it easier for us to test on the game (will also keep the value for `<TromboneTootDir>` as some sort of default value).
Everything else looks good. Really sorry that this PR also cleans up our unused imports.

**Comment by hedgehog1029** [comment]
Restored the postbuild task; instead of putting paths in the csproj perhaps they can go in local build settings? My IDE has a project-local settings page for this:

MSBuild global properties

**Comment by clydejallorina** [comment]
Could be better there, although at the moment we just have our own personal `TootTally.csproj.user` files that just set the properties to the values that we want them to be. It's a part of the `.gitignore` so it isn't being committed here. Is that what that's doing or is it a different thing altogether?

**Comment by clydejallorina** [comment]
(@Electrostats says it's easier there so yep!)

**Comment by hedgehog1029** [comment]
I think that should continue working with this config! `Directory.build.props` is another option as well

**Review by clydejallorina — APPROVED** [review]
Approved for PR

**Comment by clydejallorina** [comment]
Tested in full with multiple charts on current branch, looking good. Good for TrombLoader v2 release.

**Pull request merged**
